// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus():Promise<void>;

export function Pause():Promise<void>;

export function Reset():Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
